### ISSUE TITLE
Roadmap - 2021

### ISSUE THREAD

**Issue by errbufferoverfl** [errbufferoverfl/Html2GeminiPy#1]
The following is a list of known issues and improvements I'd like to work on in the coming 12 months.
Pull-requests welcome. :shipit:

- [ ] Unit tests
- [ ] Improve handling of reStructuredText directives and admonitions
- [ ] Implement feature to convert reStructuredText images to Gemini image
- [ ] Improve the formatting of `gmi` files
- [ ] Build into wheel or some other easy installer
- [ ] Sphinx plugin _maybe_
